import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { DrawerProvider } from "@/components/DrawerContext";
import Drawer from "@/components/Drawer";
import { SocketProvider } from "@/app/SocketContext";
import "./globals.css";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { PopupWidget } from "@/components/PopupWidget";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system">
          <SocketProvider>
            <DrawerProvider>
              <Navbar />

              <Drawer />
              <main>{children}</main>
              <Footer />
              <PopupWidget />
            </DrawerProvider>
          </SocketProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
